version: "3"

services:
  typesense:
    image: typesense/typesense:27.1
    container_name: "typesense"
    ports:
      - "8108:8108"
    volumes:
      - data-dir:/data
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
    restart: "no"

volumes:
  data-dir: